### ISSUE TITLE
Whenever I run this it generates the CSV but there is no info in the file any ideas on how to fix this?

### ISSUE THREAD

**Issue by bcarney19** [adinutzyc21/apartments-scraper#6]

**Comment by laundry-96** [comment]
Did you set up the config.ini correctly?

**Comment by zcareyltu** [comment]
Yeah I had the same issue

**Comment by adinutzyc21** [comment]
Added an update. Unfortunately, https://www.apartments.com/robots.txt prevents scraping so this won't work anymore. I tried to look up ways around it but I couldn't figure it out. If anyone has any idea, I welcome a PR!
